server:
  port: 8066
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_route #权限模块路由
          uri: http://localhost:8083 #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/auth/**
        - id: actor_route #演员模块
          uri: http://localhost:8081
          predicates:
            - Path=/actor/**
        - id: auth # 登录登出
          uri: http://localhost:8083
          predicates: # 断言，路径相匹配的进行路由
            - Path=/log**
#      discovery:
#        locator:
#          enabled: true #开启从注册中心动态创建路由的功能,默认情况下api-gateway会根据注册中心注册的服务列表，以服务名为路径创建动态路由
#          lower-case-service-id: true #使用小写服务名，默认是大写
eureka:
  instance:
    #续约间隔心跳时间
    lease-renewal-interval-in-seconds: 5
    #续约过期时间
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://peer1:8666/eureka/,http://peer2:8777/eureka/
    #开启健康检查状态上报
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: debug
