package com.still.rms.mbg.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table actor
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Actor implements Serializable {
    @ApiModelProperty(value = "演员id")
    private Integer id;

    @ApiModelProperty(value = "姓名")
    private String name;

    @ApiModelProperty(value = "别名")
    private String aliase;

    @ApiModelProperty(value = "性别")
    private Integer sex;

    @ApiModelProperty(value = "国家")
    private Integer country;

    @ApiModelProperty(value = "出生日期")
    private Date birthdate;

    @ApiModelProperty(value = "出道日期")
    private Date debutdate;

    @ApiModelProperty(value = "身高 (cm)")
    private Integer height;

    @ApiModelProperty(value = "体重 (kg)")
    private Integer weight;

    @ApiModelProperty(value = "CUP")
    private Integer cup;

    @ApiModelProperty(value = "3C")
    private String threecircles;

    @ApiModelProperty(value = "头像名称")
    private String head;

    @ApiModelProperty(value = "文件存储相对路径")
    private String actordir;

    @ApiModelProperty(value = "星级")
    private Integer star;

    @ApiModelProperty(value = "用户启用状态：0->禁用；1->启用")
    private Integer status;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "更新时间")
    private Date modifyTime;

    @ApiModelProperty(value = "简介")
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table actor
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.id
     *
     * @return the value of actor.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.id
     *
     * @param id the value for actor.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.name
     *
     * @return the value of actor.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.name
     *
     * @param name the value for actor.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.aliase
     *
     * @return the value of actor.aliase
     *
     * @mbggenerated
     */
    public String getAliase() {
        return aliase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.aliase
     *
     * @param aliase the value for actor.aliase
     *
     * @mbggenerated
     */
    public void setAliase(String aliase) {
        this.aliase = aliase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.sex
     *
     * @return the value of actor.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.sex
     *
     * @param sex the value for actor.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.country
     *
     * @return the value of actor.country
     *
     * @mbggenerated
     */
    public Integer getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.country
     *
     * @param country the value for actor.country
     *
     * @mbggenerated
     */
    public void setCountry(Integer country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.birthdate
     *
     * @return the value of actor.birthdate
     *
     * @mbggenerated
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.birthdate
     *
     * @param birthdate the value for actor.birthdate
     *
     * @mbggenerated
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.debutdate
     *
     * @return the value of actor.debutdate
     *
     * @mbggenerated
     */
    public Date getDebutdate() {
        return debutdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.debutdate
     *
     * @param debutdate the value for actor.debutdate
     *
     * @mbggenerated
     */
    public void setDebutdate(Date debutdate) {
        this.debutdate = debutdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.height
     *
     * @return the value of actor.height
     *
     * @mbggenerated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.height
     *
     * @param height the value for actor.height
     *
     * @mbggenerated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.weight
     *
     * @return the value of actor.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.weight
     *
     * @param weight the value for actor.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.cup
     *
     * @return the value of actor.cup
     *
     * @mbggenerated
     */
    public Integer getCup() {
        return cup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.cup
     *
     * @param cup the value for actor.cup
     *
     * @mbggenerated
     */
    public void setCup(Integer cup) {
        this.cup = cup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.threecircles
     *
     * @return the value of actor.threecircles
     *
     * @mbggenerated
     */
    public String getThreecircles() {
        return threecircles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.threecircles
     *
     * @param threecircles the value for actor.threecircles
     *
     * @mbggenerated
     */
    public void setThreecircles(String threecircles) {
        this.threecircles = threecircles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.head
     *
     * @return the value of actor.head
     *
     * @mbggenerated
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.head
     *
     * @param head the value for actor.head
     *
     * @mbggenerated
     */
    public void setHead(String head) {
        this.head = head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.actordir
     *
     * @return the value of actor.actordir
     *
     * @mbggenerated
     */
    public String getActordir() {
        return actordir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.actordir
     *
     * @param actordir the value for actor.actordir
     *
     * @mbggenerated
     */
    public void setActordir(String actordir) {
        this.actordir = actordir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.star
     *
     * @return the value of actor.star
     *
     * @mbggenerated
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.star
     *
     * @param star the value for actor.star
     *
     * @mbggenerated
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.status
     *
     * @return the value of actor.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.status
     *
     * @param status the value for actor.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.create_time
     *
     * @return the value of actor.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.create_time
     *
     * @param createTime the value for actor.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.modify_time
     *
     * @return the value of actor.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.modify_time
     *
     * @param modifyTime the value for actor.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.describe
     *
     * @return the value of actor.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.describe
     *
     * @param describe the value for actor.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", aliase=").append(aliase);
        sb.append(", sex=").append(sex);
        sb.append(", country=").append(country);
        sb.append(", birthdate=").append(birthdate);
        sb.append(", debutdate=").append(debutdate);
        sb.append(", height=").append(height);
        sb.append(", weight=").append(weight);
        sb.append(", cup=").append(cup);
        sb.append(", threecircles=").append(threecircles);
        sb.append(", head=").append(head);
        sb.append(", actordir=").append(actordir);
        sb.append(", star=").append(star);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", describe=").append(describe);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}