package com.still.rms.mbg.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dictinfo
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Dictinfo implements Serializable {
    @ApiModelProperty(value = "主键")
    private Integer id;

    @ApiModelProperty(value = "数据字典类型ID")
    private Integer dicttypeId;

    @ApiModelProperty(value = "字典信息")
    private String name;

    @ApiModelProperty(value = "排序")
    private Integer order;

    @ApiModelProperty(value = "父节点ID，根节点为0")
    private Integer parentId;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "更新时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dictinfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.id
     *
     * @return the value of dictinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.id
     *
     * @param id the value for dictinfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.dicttype_id
     *
     * @return the value of dictinfo.dicttype_id
     *
     * @mbggenerated
     */
    public Integer getDicttypeId() {
        return dicttypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.dicttype_id
     *
     * @param dicttypeId the value for dictinfo.dicttype_id
     *
     * @mbggenerated
     */
    public void setDicttypeId(Integer dicttypeId) {
        this.dicttypeId = dicttypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.name
     *
     * @return the value of dictinfo.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.name
     *
     * @param name the value for dictinfo.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.order
     *
     * @return the value of dictinfo.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.order
     *
     * @param order the value for dictinfo.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.parent_id
     *
     * @return the value of dictinfo.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.parent_id
     *
     * @param parentId the value for dictinfo.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.create_time
     *
     * @return the value of dictinfo.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.create_time
     *
     * @param createTime the value for dictinfo.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.update_time
     *
     * @return the value of dictinfo.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.update_time
     *
     * @param updateTime the value for dictinfo.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dicttypeId=").append(dicttypeId);
        sb.append(", name=").append(name);
        sb.append(", order=").append(order);
        sb.append(", parentId=").append(parentId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}