package com.still.rms.mbg.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table image
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Image implements Serializable {
    @ApiModelProperty(value = "id")
    private Integer id;

    @ApiModelProperty(value = "标题")
    private String title;

    @ApiModelProperty(value = "编号")
    private String designation;

    @ApiModelProperty(value = "发行日期")
    private Date issuingdate;

    @ApiModelProperty(value = "导演")
    private String director;

    @ApiModelProperty(value = "制造商")
    private String manufacturer;

    @ApiModelProperty(value = "发型商")
    private String publisher;

    @ApiModelProperty(value = "得分")
    private Integer score;

    @ApiModelProperty(value = "大小 单位Gb")
    private Double videosize;

    @ApiModelProperty(value = "海报名称")
    private String poster;

    @ApiModelProperty(value = "主题分类")
    private Integer theme;

    @ApiModelProperty(value = "标记")
    private Integer mark;

    @ApiModelProperty(value = "相对路径")
    private String videodir;

    @ApiModelProperty(value = "国别")
    private Integer country;

    @ApiModelProperty(value = "创建时间")
    private Date cteateTime;

    @ApiModelProperty(value = "更新时间")
    private Date modifyTime;

    @ApiModelProperty(value = "描述")
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.title
     *
     * @return the value of image.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.title
     *
     * @param title the value for image.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.designation
     *
     * @return the value of image.designation
     *
     * @mbggenerated
     */
    public String getDesignation() {
        return designation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.designation
     *
     * @param designation the value for image.designation
     *
     * @mbggenerated
     */
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.issuingdate
     *
     * @return the value of image.issuingdate
     *
     * @mbggenerated
     */
    public Date getIssuingdate() {
        return issuingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.issuingdate
     *
     * @param issuingdate the value for image.issuingdate
     *
     * @mbggenerated
     */
    public void setIssuingdate(Date issuingdate) {
        this.issuingdate = issuingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.director
     *
     * @return the value of image.director
     *
     * @mbggenerated
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.director
     *
     * @param director the value for image.director
     *
     * @mbggenerated
     */
    public void setDirector(String director) {
        this.director = director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.manufacturer
     *
     * @return the value of image.manufacturer
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.manufacturer
     *
     * @param manufacturer the value for image.manufacturer
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.publisher
     *
     * @return the value of image.publisher
     *
     * @mbggenerated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.publisher
     *
     * @param publisher the value for image.publisher
     *
     * @mbggenerated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.score
     *
     * @return the value of image.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.score
     *
     * @param score the value for image.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.videosize
     *
     * @return the value of image.videosize
     *
     * @mbggenerated
     */
    public Double getVideosize() {
        return videosize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.videosize
     *
     * @param videosize the value for image.videosize
     *
     * @mbggenerated
     */
    public void setVideosize(Double videosize) {
        this.videosize = videosize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.poster
     *
     * @return the value of image.poster
     *
     * @mbggenerated
     */
    public String getPoster() {
        return poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.poster
     *
     * @param poster the value for image.poster
     *
     * @mbggenerated
     */
    public void setPoster(String poster) {
        this.poster = poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.theme
     *
     * @return the value of image.theme
     *
     * @mbggenerated
     */
    public Integer getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.theme
     *
     * @param theme the value for image.theme
     *
     * @mbggenerated
     */
    public void setTheme(Integer theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.mark
     *
     * @return the value of image.mark
     *
     * @mbggenerated
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.mark
     *
     * @param mark the value for image.mark
     *
     * @mbggenerated
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.videodir
     *
     * @return the value of image.videodir
     *
     * @mbggenerated
     */
    public String getVideodir() {
        return videodir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.videodir
     *
     * @param videodir the value for image.videodir
     *
     * @mbggenerated
     */
    public void setVideodir(String videodir) {
        this.videodir = videodir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.country
     *
     * @return the value of image.country
     *
     * @mbggenerated
     */
    public Integer getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.country
     *
     * @param country the value for image.country
     *
     * @mbggenerated
     */
    public void setCountry(Integer country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.cteate_time
     *
     * @return the value of image.cteate_time
     *
     * @mbggenerated
     */
    public Date getCteateTime() {
        return cteateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.cteate_time
     *
     * @param cteateTime the value for image.cteate_time
     *
     * @mbggenerated
     */
    public void setCteateTime(Date cteateTime) {
        this.cteateTime = cteateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.modify_time
     *
     * @return the value of image.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.modify_time
     *
     * @param modifyTime the value for image.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.describe
     *
     * @return the value of image.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.describe
     *
     * @param describe the value for image.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", designation=").append(designation);
        sb.append(", issuingdate=").append(issuingdate);
        sb.append(", director=").append(director);
        sb.append(", manufacturer=").append(manufacturer);
        sb.append(", publisher=").append(publisher);
        sb.append(", score=").append(score);
        sb.append(", videosize=").append(videosize);
        sb.append(", poster=").append(poster);
        sb.append(", theme=").append(theme);
        sb.append(", mark=").append(mark);
        sb.append(", videodir=").append(videodir);
        sb.append(", country=").append(country);
        sb.append(", cteateTime=").append(cteateTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", describe=").append(describe);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}