package com.still.rms.mbg.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table log
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Log implements Serializable {
    @ApiModelProperty(value = "主键")
    private Long id;

    @ApiModelProperty(value = "访问用户ID")
    private Long userid;

    @ApiModelProperty(value = "访问用户名称")
    private String username;

    @ApiModelProperty(value = "访问用户昵称")
    private String nickname;

    @ApiModelProperty(value = "操作时间戳")
    private Date startTime;

    @ApiModelProperty(value = "消耗时间")
    private Integer spendTime;

    @ApiModelProperty(value = "操作描述")
    private String description;

    @ApiModelProperty(value = "根路径")
    private String basePath;

    @ApiModelProperty(value = "URI")
    private String uri;

    @ApiModelProperty(value = "URL")
    private String url;

    @ApiModelProperty(value = "请求类型")
    private String method;

    @ApiModelProperty(value = "远程用户")
    private String remoteUser;

    @ApiModelProperty(value = "远程IP")
    private String remoteIp;

    @ApiModelProperty(value = "远程端口")
    private Integer remotePort;

    @ApiModelProperty(value = "远程地址")
    private String remoteAddr;

    @ApiModelProperty(value = "请求参数")
    private String parameter;

    @ApiModelProperty(value = "请求返回的结果")
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.userId
     *
     * @return the value of log.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.userId
     *
     * @param userid the value for log.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.username
     *
     * @return the value of log.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.username
     *
     * @param username the value for log.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.nickname
     *
     * @return the value of log.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.nickname
     *
     * @param nickname the value for log.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.start_time
     *
     * @return the value of log.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.start_time
     *
     * @param startTime the value for log.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.spend_time
     *
     * @return the value of log.spend_time
     *
     * @mbggenerated
     */
    public Integer getSpendTime() {
        return spendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.spend_time
     *
     * @param spendTime the value for log.spend_time
     *
     * @mbggenerated
     */
    public void setSpendTime(Integer spendTime) {
        this.spendTime = spendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.description
     *
     * @return the value of log.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.description
     *
     * @param description the value for log.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.base_path
     *
     * @return the value of log.base_path
     *
     * @mbggenerated
     */
    public String getBasePath() {
        return basePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.base_path
     *
     * @param basePath the value for log.base_path
     *
     * @mbggenerated
     */
    public void setBasePath(String basePath) {
        this.basePath = basePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.uri
     *
     * @return the value of log.uri
     *
     * @mbggenerated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.uri
     *
     * @param uri the value for log.uri
     *
     * @mbggenerated
     */
    public void setUri(String uri) {
        this.uri = uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.url
     *
     * @return the value of log.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.url
     *
     * @param url the value for log.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.method
     *
     * @return the value of log.method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.method
     *
     * @param method the value for log.method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.remote_user
     *
     * @return the value of log.remote_user
     *
     * @mbggenerated
     */
    public String getRemoteUser() {
        return remoteUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.remote_user
     *
     * @param remoteUser the value for log.remote_user
     *
     * @mbggenerated
     */
    public void setRemoteUser(String remoteUser) {
        this.remoteUser = remoteUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.remote_ip
     *
     * @return the value of log.remote_ip
     *
     * @mbggenerated
     */
    public String getRemoteIp() {
        return remoteIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.remote_ip
     *
     * @param remoteIp the value for log.remote_ip
     *
     * @mbggenerated
     */
    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.remote_port
     *
     * @return the value of log.remote_port
     *
     * @mbggenerated
     */
    public Integer getRemotePort() {
        return remotePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.remote_port
     *
     * @param remotePort the value for log.remote_port
     *
     * @mbggenerated
     */
    public void setRemotePort(Integer remotePort) {
        this.remotePort = remotePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.remote_addr
     *
     * @return the value of log.remote_addr
     *
     * @mbggenerated
     */
    public String getRemoteAddr() {
        return remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.remote_addr
     *
     * @param remoteAddr the value for log.remote_addr
     *
     * @mbggenerated
     */
    public void setRemoteAddr(String remoteAddr) {
        this.remoteAddr = remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.parameter
     *
     * @return the value of log.parameter
     *
     * @mbggenerated
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.parameter
     *
     * @param parameter the value for log.parameter
     *
     * @mbggenerated
     */
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.result
     *
     * @return the value of log.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.result
     *
     * @param result the value for log.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", nickname=").append(nickname);
        sb.append(", startTime=").append(startTime);
        sb.append(", spendTime=").append(spendTime);
        sb.append(", description=").append(description);
        sb.append(", basePath=").append(basePath);
        sb.append(", uri=").append(uri);
        sb.append(", url=").append(url);
        sb.append(", method=").append(method);
        sb.append(", remoteUser=").append(remoteUser);
        sb.append(", remoteIp=").append(remoteIp);
        sb.append(", remotePort=").append(remotePort);
        sb.append(", remoteAddr=").append(remoteAddr);
        sb.append(", parameter=").append(parameter);
        sb.append(", result=").append(result);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}