package com.still.rms.mbg.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table resource
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Resource implements Serializable {
    @ApiModelProperty(value = "id")
    private Long id;

    @ApiModelProperty(value = "标题")
    private String title;

    @ApiModelProperty(value = "编号")
    private String designation;

    @ApiModelProperty(value = "发行日期")
    private Date issuingdate;

    @ApiModelProperty(value = "播放时长 单位:分钟")
    private Integer duration;

    @ApiModelProperty(value = "导演")
    private String director;

    @ApiModelProperty(value = "制造商")
    private String manufacturer;

    @ApiModelProperty(value = "发型商")
    private String publisher;

    @ApiModelProperty(value = "得分")
    private Double score;

    @ApiModelProperty(value = "资源文件类型：0-视频；1-图片")
    private Integer type;

    @ApiModelProperty(value = "资源文件大小 单位:GB")
    private Double size;

    @ApiModelProperty(value = "视频文件格式")
    private Integer videotype;

    @ApiModelProperty(value = "视频名称")
    private String videoname;

    @ApiModelProperty(value = "预览视频名称")
    private String samplevideo;

    @ApiModelProperty(value = "预览视频名称URL")
    private String samplevideoUrl;

    @ApiModelProperty(value = "海报名称")
    private String poster;

    @ApiModelProperty(value = "海报名称")
    private String posterFull;

    @ApiModelProperty(value = "主题分类")
    private Integer theme;

    @ApiModelProperty(value = "标记")
    private Integer mark;

    @ApiModelProperty(value = "文件存储相对路径")
    private String resourcedir;

    @ApiModelProperty(value = "国别")
    private Integer country;

    @ApiModelProperty(value = "用户启用状态：0->禁用；1->启用")
    private Integer status;

    @ApiModelProperty(value = "创建时间")
    private Date cteateTime;

    @ApiModelProperty(value = "更新时间")
    private Date modifyTime;

    @ApiModelProperty(value = "简介")
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.title
     *
     * @return the value of resource.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.title
     *
     * @param title the value for resource.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.designation
     *
     * @return the value of resource.designation
     *
     * @mbggenerated
     */
    public String getDesignation() {
        return designation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.designation
     *
     * @param designation the value for resource.designation
     *
     * @mbggenerated
     */
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.issuingdate
     *
     * @return the value of resource.issuingdate
     *
     * @mbggenerated
     */
    public Date getIssuingdate() {
        return issuingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.issuingdate
     *
     * @param issuingdate the value for resource.issuingdate
     *
     * @mbggenerated
     */
    public void setIssuingdate(Date issuingdate) {
        this.issuingdate = issuingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.duration
     *
     * @return the value of resource.duration
     *
     * @mbggenerated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.duration
     *
     * @param duration the value for resource.duration
     *
     * @mbggenerated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.director
     *
     * @return the value of resource.director
     *
     * @mbggenerated
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.director
     *
     * @param director the value for resource.director
     *
     * @mbggenerated
     */
    public void setDirector(String director) {
        this.director = director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.manufacturer
     *
     * @return the value of resource.manufacturer
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.manufacturer
     *
     * @param manufacturer the value for resource.manufacturer
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.publisher
     *
     * @return the value of resource.publisher
     *
     * @mbggenerated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.publisher
     *
     * @param publisher the value for resource.publisher
     *
     * @mbggenerated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.score
     *
     * @return the value of resource.score
     *
     * @mbggenerated
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.score
     *
     * @param score the value for resource.score
     *
     * @mbggenerated
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.type
     *
     * @return the value of resource.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.type
     *
     * @param type the value for resource.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.size
     *
     * @return the value of resource.size
     *
     * @mbggenerated
     */
    public Double getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.size
     *
     * @param size the value for resource.size
     *
     * @mbggenerated
     */
    public void setSize(Double size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.videotype
     *
     * @return the value of resource.videotype
     *
     * @mbggenerated
     */
    public Integer getVideotype() {
        return videotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.videotype
     *
     * @param videotype the value for resource.videotype
     *
     * @mbggenerated
     */
    public void setVideotype(Integer videotype) {
        this.videotype = videotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.videoname
     *
     * @return the value of resource.videoname
     *
     * @mbggenerated
     */
    public String getVideoname() {
        return videoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.videoname
     *
     * @param videoname the value for resource.videoname
     *
     * @mbggenerated
     */
    public void setVideoname(String videoname) {
        this.videoname = videoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.samplevideo
     *
     * @return the value of resource.samplevideo
     *
     * @mbggenerated
     */
    public String getSamplevideo() {
        return samplevideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.samplevideo
     *
     * @param samplevideo the value for resource.samplevideo
     *
     * @mbggenerated
     */
    public void setSamplevideo(String samplevideo) {
        this.samplevideo = samplevideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.samplevideo_url
     *
     * @return the value of resource.samplevideo_url
     *
     * @mbggenerated
     */
    public String getSamplevideoUrl() {
        return samplevideoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.samplevideo_url
     *
     * @param samplevideoUrl the value for resource.samplevideo_url
     *
     * @mbggenerated
     */
    public void setSamplevideoUrl(String samplevideoUrl) {
        this.samplevideoUrl = samplevideoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.poster
     *
     * @return the value of resource.poster
     *
     * @mbggenerated
     */
    public String getPoster() {
        return poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.poster
     *
     * @param poster the value for resource.poster
     *
     * @mbggenerated
     */
    public void setPoster(String poster) {
        this.poster = poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.poster_full
     *
     * @return the value of resource.poster_full
     *
     * @mbggenerated
     */
    public String getPosterFull() {
        return posterFull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.poster_full
     *
     * @param posterFull the value for resource.poster_full
     *
     * @mbggenerated
     */
    public void setPosterFull(String posterFull) {
        this.posterFull = posterFull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.theme
     *
     * @return the value of resource.theme
     *
     * @mbggenerated
     */
    public Integer getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.theme
     *
     * @param theme the value for resource.theme
     *
     * @mbggenerated
     */
    public void setTheme(Integer theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.mark
     *
     * @return the value of resource.mark
     *
     * @mbggenerated
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.mark
     *
     * @param mark the value for resource.mark
     *
     * @mbggenerated
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resourcedir
     *
     * @return the value of resource.resourcedir
     *
     * @mbggenerated
     */
    public String getResourcedir() {
        return resourcedir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resourcedir
     *
     * @param resourcedir the value for resource.resourcedir
     *
     * @mbggenerated
     */
    public void setResourcedir(String resourcedir) {
        this.resourcedir = resourcedir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.country
     *
     * @return the value of resource.country
     *
     * @mbggenerated
     */
    public Integer getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.country
     *
     * @param country the value for resource.country
     *
     * @mbggenerated
     */
    public void setCountry(Integer country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.status
     *
     * @return the value of resource.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.status
     *
     * @param status the value for resource.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.cteate_time
     *
     * @return the value of resource.cteate_time
     *
     * @mbggenerated
     */
    public Date getCteateTime() {
        return cteateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.cteate_time
     *
     * @param cteateTime the value for resource.cteate_time
     *
     * @mbggenerated
     */
    public void setCteateTime(Date cteateTime) {
        this.cteateTime = cteateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.modify_time
     *
     * @return the value of resource.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.modify_time
     *
     * @param modifyTime the value for resource.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.describe
     *
     * @return the value of resource.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.describe
     *
     * @param describe the value for resource.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", designation=").append(designation);
        sb.append(", issuingdate=").append(issuingdate);
        sb.append(", duration=").append(duration);
        sb.append(", director=").append(director);
        sb.append(", manufacturer=").append(manufacturer);
        sb.append(", publisher=").append(publisher);
        sb.append(", score=").append(score);
        sb.append(", type=").append(type);
        sb.append(", size=").append(size);
        sb.append(", videotype=").append(videotype);
        sb.append(", videoname=").append(videoname);
        sb.append(", samplevideo=").append(samplevideo);
        sb.append(", samplevideoUrl=").append(samplevideoUrl);
        sb.append(", poster=").append(poster);
        sb.append(", posterFull=").append(posterFull);
        sb.append(", theme=").append(theme);
        sb.append(", mark=").append(mark);
        sb.append(", resourcedir=").append(resourcedir);
        sb.append(", country=").append(country);
        sb.append(", status=").append(status);
        sb.append(", cteateTime=").append(cteateTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", describe=").append(describe);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}