package com.still.aikandy.mbg.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table video
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Video implements Serializable {
    @ApiModelProperty(value = "视频id")
    private Integer id;

    @ApiModelProperty(value = "标题")
    private String title;

    @ApiModelProperty(value = "编号")
    private String designation;

    @ApiModelProperty(value = "发行日期")
    private Date issuingdate;

    @ApiModelProperty(value = "播放时长 单位:分钟")
    private Integer duration;

    @ApiModelProperty(value = "导演")
    private String director;

    @ApiModelProperty(value = "制造商")
    private String manufacturer;

    @ApiModelProperty(value = "发型商")
    private String publisher;

    @ApiModelProperty(value = "得分")
    private Integer score;

    @ApiModelProperty(value = "视频大小 单位Gb")
    private Double videosize;

    @ApiModelProperty(value = "视频文件格式")
    private Integer videotype;

    @ApiModelProperty(value = "视频名称")
    private String videoname;

    @ApiModelProperty(value = "预览视频名称")
    private String samplevideo;

    @ApiModelProperty(value = "海报名称")
    private String poster;

    @ApiModelProperty(value = "主题分类")
    private Integer theme;

    @ApiModelProperty(value = "标记")
    private Integer mark;

    @ApiModelProperty(value = "相对路径")
    private String videodir;

    @ApiModelProperty(value = "国别")
    private Integer country;

    @ApiModelProperty(value = "创建时间")
    private Date cteateTime;

    @ApiModelProperty(value = "更新时间")
    private Date modifyTime;

    @ApiModelProperty(value = "视频描述")
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.title
     *
     * @return the value of video.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.title
     *
     * @param title the value for video.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.designation
     *
     * @return the value of video.designation
     *
     * @mbggenerated
     */
    public String getDesignation() {
        return designation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.designation
     *
     * @param designation the value for video.designation
     *
     * @mbggenerated
     */
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.issuingdate
     *
     * @return the value of video.issuingdate
     *
     * @mbggenerated
     */
    public Date getIssuingdate() {
        return issuingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.issuingdate
     *
     * @param issuingdate the value for video.issuingdate
     *
     * @mbggenerated
     */
    public void setIssuingdate(Date issuingdate) {
        this.issuingdate = issuingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.duration
     *
     * @return the value of video.duration
     *
     * @mbggenerated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.duration
     *
     * @param duration the value for video.duration
     *
     * @mbggenerated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.director
     *
     * @return the value of video.director
     *
     * @mbggenerated
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.director
     *
     * @param director the value for video.director
     *
     * @mbggenerated
     */
    public void setDirector(String director) {
        this.director = director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.manufacturer
     *
     * @return the value of video.manufacturer
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.manufacturer
     *
     * @param manufacturer the value for video.manufacturer
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.publisher
     *
     * @return the value of video.publisher
     *
     * @mbggenerated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.publisher
     *
     * @param publisher the value for video.publisher
     *
     * @mbggenerated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.score
     *
     * @return the value of video.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.score
     *
     * @param score the value for video.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.videosize
     *
     * @return the value of video.videosize
     *
     * @mbggenerated
     */
    public Double getVideosize() {
        return videosize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.videosize
     *
     * @param videosize the value for video.videosize
     *
     * @mbggenerated
     */
    public void setVideosize(Double videosize) {
        this.videosize = videosize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.videotype
     *
     * @return the value of video.videotype
     *
     * @mbggenerated
     */
    public Integer getVideotype() {
        return videotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.videotype
     *
     * @param videotype the value for video.videotype
     *
     * @mbggenerated
     */
    public void setVideotype(Integer videotype) {
        this.videotype = videotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.videoname
     *
     * @return the value of video.videoname
     *
     * @mbggenerated
     */
    public String getVideoname() {
        return videoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.videoname
     *
     * @param videoname the value for video.videoname
     *
     * @mbggenerated
     */
    public void setVideoname(String videoname) {
        this.videoname = videoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.samplevideo
     *
     * @return the value of video.samplevideo
     *
     * @mbggenerated
     */
    public String getSamplevideo() {
        return samplevideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.samplevideo
     *
     * @param samplevideo the value for video.samplevideo
     *
     * @mbggenerated
     */
    public void setSamplevideo(String samplevideo) {
        this.samplevideo = samplevideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.poster
     *
     * @return the value of video.poster
     *
     * @mbggenerated
     */
    public String getPoster() {
        return poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.poster
     *
     * @param poster the value for video.poster
     *
     * @mbggenerated
     */
    public void setPoster(String poster) {
        this.poster = poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.theme
     *
     * @return the value of video.theme
     *
     * @mbggenerated
     */
    public Integer getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.theme
     *
     * @param theme the value for video.theme
     *
     * @mbggenerated
     */
    public void setTheme(Integer theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.mark
     *
     * @return the value of video.mark
     *
     * @mbggenerated
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.mark
     *
     * @param mark the value for video.mark
     *
     * @mbggenerated
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.videodir
     *
     * @return the value of video.videodir
     *
     * @mbggenerated
     */
    public String getVideodir() {
        return videodir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.videodir
     *
     * @param videodir the value for video.videodir
     *
     * @mbggenerated
     */
    public void setVideodir(String videodir) {
        this.videodir = videodir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.country
     *
     * @return the value of video.country
     *
     * @mbggenerated
     */
    public Integer getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.country
     *
     * @param country the value for video.country
     *
     * @mbggenerated
     */
    public void setCountry(Integer country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.cteate_time
     *
     * @return the value of video.cteate_time
     *
     * @mbggenerated
     */
    public Date getCteateTime() {
        return cteateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.cteate_time
     *
     * @param cteateTime the value for video.cteate_time
     *
     * @mbggenerated
     */
    public void setCteateTime(Date cteateTime) {
        this.cteateTime = cteateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.modify_time
     *
     * @return the value of video.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.modify_time
     *
     * @param modifyTime the value for video.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.describe
     *
     * @return the value of video.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.describe
     *
     * @param describe the value for video.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", designation=").append(designation);
        sb.append(", issuingdate=").append(issuingdate);
        sb.append(", duration=").append(duration);
        sb.append(", director=").append(director);
        sb.append(", manufacturer=").append(manufacturer);
        sb.append(", publisher=").append(publisher);
        sb.append(", score=").append(score);
        sb.append(", videosize=").append(videosize);
        sb.append(", videotype=").append(videotype);
        sb.append(", videoname=").append(videoname);
        sb.append(", samplevideo=").append(samplevideo);
        sb.append(", poster=").append(poster);
        sb.append(", theme=").append(theme);
        sb.append(", mark=").append(mark);
        sb.append(", videodir=").append(videodir);
        sb.append(", country=").append(country);
        sb.append(", cteateTime=").append(cteateTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", describe=").append(describe);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}