package com.still.rms.mbg.mapper;

import com.still.rms.mbg.model.AuthRoleMenu;

public interface AuthRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_menu
     *
     * @mbggenerated
     */
    int insert(AuthRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_menu
     *
     * @mbggenerated
     */
    int insertSelective(AuthRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_menu
     *
     * @mbggenerated
     */
    AuthRoleMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthRoleMenu record);
}