package com.still.rms.mbg.mapper;

import com.still.rms.mbg.model.AuthResourceCategory;

public interface AuthResourceCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource_category
     *
     * @mbggenerated
     */
    int insert(AuthResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource_category
     *
     * @mbggenerated
     */
    int insertSelective(AuthResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource_category
     *
     * @mbggenerated
     */
    AuthResourceCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthResourceCategory record);
}