package com.still.rms.mbg.mapper;

import com.still.rms.mbg.model.AuthRoleResource;

public interface AuthRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbggenerated
     */
    int insert(AuthRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbggenerated
     */
    int insertSelective(AuthRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbggenerated
     */
    AuthRoleResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthRoleResource record);
}