package com.still.rms.mbg.mapper;

import com.still.rms.mbg.model.RealtionActorImage;

public interface RealtionActorImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_image
     *
     * @mbggenerated
     */
    int insert(RealtionActorImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_image
     *
     * @mbggenerated
     */
    int insertSelective(RealtionActorImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_image
     *
     * @mbggenerated
     */
    RealtionActorImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RealtionActorImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RealtionActorImage record);
}