package com.still.rms.mbg.mapper;

import com.still.rms.mbg.model.RealtionActorResource;

public interface RealtionActorResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_resource
     *
     * @mbggenerated
     */
    int insert(RealtionActorResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_resource
     *
     * @mbggenerated
     */
    int insertSelective(RealtionActorResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_resource
     *
     * @mbggenerated
     */
    RealtionActorResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RealtionActorResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RealtionActorResource record);
}