package com.still.rms.mbg.mapper;

import com.still.rms.mbg.model.RealtionActorVideo;

public interface RealtionActorVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_video
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_video
     *
     * @mbggenerated
     */
    int insert(RealtionActorVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_video
     *
     * @mbggenerated
     */
    int insertSelective(RealtionActorVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_video
     *
     * @mbggenerated
     */
    RealtionActorVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_video
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RealtionActorVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_actor_video
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RealtionActorVideo record);
}