package com.still.rms.mbg.mapper;

import com.still.rms.mbg.model.RealtionVideoDictinfo;

public interface RealtionVideoDictinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_video_dictinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_video_dictinfo
     *
     * @mbggenerated
     */
    int insert(RealtionVideoDictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_video_dictinfo
     *
     * @mbggenerated
     */
    int insertSelective(RealtionVideoDictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_video_dictinfo
     *
     * @mbggenerated
     */
    RealtionVideoDictinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_video_dictinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RealtionVideoDictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realtion_video_dictinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RealtionVideoDictinfo record);
}