package com.still.rms.mbg.mapper;

import com.still.rms.mbg.model.RelationResourceTag;

public interface RelationResourceTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_resource_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_resource_tag
     *
     * @mbggenerated
     */
    int insert(RelationResourceTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_resource_tag
     *
     * @mbggenerated
     */
    int insertSelective(RelationResourceTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_resource_tag
     *
     * @mbggenerated
     */
    RelationResourceTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_resource_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelationResourceTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_resource_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelationResourceTag record);
}