package com.still.aikandy.mbg.mapper;

import com.still.aikandy.mbg.model.AuthMenu;

public interface AuthMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbggenerated
     */
    int insert(AuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbggenerated
     */
    int insertSelective(AuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbggenerated
     */
    AuthMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthMenu record);
}