package com.still.aikandy.mbg.mapper;

import com.still.aikandy.mbg.model.AuthResource;

public interface AuthResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbggenerated
     */
    int insert(AuthResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbggenerated
     */
    int insertSelective(AuthResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbggenerated
     */
    AuthResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthResource record);
}