package com.still.aikandy.mbg.mapper;

import com.still.aikandy.mbg.model.AuthRole;

public interface AuthRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated
     */
    int insert(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated
     */
    int insertSelective(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated
     */
    AuthRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthRole record);
}