package com.still.aikandy.mbg.mapper;

import com.still.aikandy.mbg.model.AuthUserRole;

public interface AuthUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbggenerated
     */
    int insert(AuthUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbggenerated
     */
    int insertSelective(AuthUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbggenerated
     */
    AuthUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthUserRole record);
}