package com.still.aikandy.mbg.mapper;

import com.still.aikandy.mbg.model.Dictinfo;

public interface DictinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbggenerated
     */
    int insert(Dictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbggenerated
     */
    int insertSelective(Dictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbggenerated
     */
    Dictinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dictinfo record);
}